kind = "web"
previewPath = "/"
title = "BlackPanda"
version = "1.0.0"
id = "artifacts/blackpanda"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21927

[services.development]
run = "pnpm --filter @workspace/blackpanda run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/blackpanda", "run", "build" ]
publicDir = "artifacts/blackpanda/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21927"
BASE_PATH = "/"
